version: "3"

services:
  app:
    build: .
    volumes:
      - .:/go/src/
    network_mode: host
  db:
    image: postgres:9.4
    restart: always
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=codepix
    ports:
      - "5432:5432"
